org.gradle.jvmargs=-Xmx2G
org.gradle.configuration-cache=true

# Fabric Properties (https://fabricmc.net/develop)
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.1
loader_version=0.16.7
mod_version=1.0.0
maven_group=com.ayan7601.blazed
archives_base_name=Blazed
baritone_version=1.21.4

# Mod Properties
mod_version=1.21.4-n-16.1
maven_group=com.ayan7601
archives_base_name=blazed
mod_name=Blazed

# Dependencies
baritone_version=1.21.4
